default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_forum_development

test:
  <<: *default
  database: web_forum_test

production:
  <<: *default
  database: web_forum_production
  username: web_forum
  password: <%= ENV["WEB_FORUM_DATABASE_PASSWORD"] %>
